name: Guardrail
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
    - fastapi
    - uvicorn[standard]
    - guardrails-ai
    - nemoguardrails
    - ollama
    - presidio-analyzer
    - presidio-anonymizer
    - spacy
    - python-dotenv
    - websockets
    - pydantic
    - typing-extensions
    - pythainlp
    - python-crfsuite
    - transformers==4.34.1
    - tokenizers==0.14.1
    - sacremoses
    - sentencepiece
